platform:ios, "7.0"
target ‘大富豪’ do
pod 'Reachability'
pod 'SBJson'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'AFNetworking'
pod 'PureLayout'
pod 'UMengSocial', '~> 5.0’
pod 'UMengAnalyticsSDK', '~> 3.6.7.0'
pod 'Masonry', '~> 1.0.0'
pod 'HMSegmentedControl', '~> 1.5.2'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Cordova'
pod 'Mantle', '~> 2.0.6'
end
